### ISSUE TITLE
Better styling of header description at different wider screen widths....

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/contemporary-grid#5]

**Comment by cmuething** [comment]
I have been playing around with the description as we switch between screen sizes and I think it might be worth exploring an option that, upon refreshing the page, the rotation (a readable range), position, and z-index of the logo, mark, and description change. This would mean fixing the width and padding of the description, possible adding a media query to adjust size before it is display:none in the skinny view. What do you think? I can try mocking that up tomorrow morning.

**Comment by bjornmeansbear** [comment]
If the layout/design is easily controlled that's fine — I think swapping those things on refresh would require a lot more design time as the ranges of options would need to be fairly preset to make sure that things will work out more or less all the time...

Anyway, randomness isn't important to me — though positioning and rotation CAN be different based on screen widths/media-queries?

**Comment by bjornmeansbear** [comment]
#2 is related
